# Generated by Django 5.2 on 2026-02-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('F', 'Film'), ('S', 'Serie'), ('D', 'Documentary')], default='F')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('birth_date', models.DateField()),
                ('cell_phone', models.CharField(max_length=14)),
            ],
        ),
    ]
