# Generated by Django 5.2 on 2026-01-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('birthday', models.DateField()),
                ('cell_phone', models.CharField(max_length=14)),
            ],
        ),
    ]
