# Generated by Django 5.2 on 2026-01-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myflix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('F', 'Film'), ('S', 'Serie'), ('D', 'Documentary')], default='F')),
            ],
        ),
    ]
