# Generated by Django 5.2 on 2026-02-01 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myflix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myflix.stream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myflix.user')),
            ],
        ),
    ]
